### ISSUE TITLE
KiteAB爬

### ISSUE THREAD

**Issue by KiteAB** [Chi-Tang-github/Arch-Linux-install-guide#1]
1  你为啥用网页操控repo？？现在不都用git的吗
2  尼玛都建了4d了  怎么还是空的

**Comment by Chi-Tang-github** [comment]
因为我是傻逼

来自 Outlook<http://aka.ms/weboutlook>
________________________________
发件人: KiteAB <notifications@github.com>
发送时间: 2020年5月14日 21:53
收件人: Chi-Tang-github/Arch-Linux-install-guide <Arch-Linux-install-guide@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [Chi-Tang-github/Arch-Linux-install-guide] 爬 (#1)


1 你为啥用网页操控repo？？现在不都用git的吗
2 尼玛都建了4d了 怎么还是空的

―
